// Synthetic 6-entry route map (the test asserts it equals its BASE_MAP constant).
export const ROUTE_MAP = [
  {
    id: 'tasks',
    from: '/tasks',
    to: '/tasks',
    kind: 'page',
    change: 'kept',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
  },
  {
    id: 'task',
    from: '/tasks/:id',
    to: '/tasks/:id',
    kind: 'page',
    change: 'kept',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: true,
    carries: [],
    stage: 'done',
    parent: 'tasks',
  },
  {
    id: 'admin',
    from: '/admin',
    to: '/admin',
    kind: 'page',
    change: 'kept',
    section: 'System',
    guard: 'admin',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
  },
  {
    id: 'review',
    from: '/review',
    to: '/review',
    kind: 'page',
    change: 'kept',
    section: 'Money',
    guard: 'member',
    gate: 'paperless',
    permanent: false,
    carries: [],
    stage: 'done',
  },
  {
    from: '/old/:id',
    to: '/tasks/:id',
    kind: 'redirect',
    change: 'redirect',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/review (Paperless off)',
    to: '/tasks',
    kind: 'redirect',
    change: 'conditional',
    section: 'Money',
    guard: 'member',
    gate: 'paperless',
    permanent: false,
    carries: ['*'],
    stage: 'done',
    match: { condition: 'paperless-off', appliesTo: ['review'] },
  },
];
