// Route map (EPIC-21, ADR-038): the runtime source of truth for every app URL.
// Pure data. Self-contained on purpose: E2E and `npm run plan:check` load this folder as source
// without a build, so it may import only from './*.js' siblings.
// Fields from/to/kind/change/section/guard/gate/permanent/carries must agree with
// plan/restructure/routemap.json (the curated record with the notes); `plan:check` enforces it.

import type { RouteMapEntry } from './types.js';

export const ROUTE_MAP = [
  {
    id: 'setup',
    from: '/setup',
    to: '/setup',
    kind: 'page',
    change: 'kept',
    section: 'Auth',
    guard: 'public',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
  },
  {
    id: 'login',
    from: '/login',
    to: '/login',
    kind: 'page',
    change: 'kept',
    section: 'Auth',
    guard: 'public',
    gate: 'none',
    permanent: false,
    carries: ['next', 'error'],
    stage: 'done',
  },
  {
    id: 'workItems',
    from: '/project/work-items',
    to: '/project/work-items',
    kind: 'page',
    change: 'kept',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['q', 'sortBy', 'sortOrder', 'page', 'pageSize', 'filters', 'group'],
    stage: 'done',
  },
  {
    id: 'workItemNew',
    from: '/project/work-items/new',
    to: '/project/work-items/new',
    kind: 'page',
    change: 'kept',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
    parent: 'workItems',
  },
  {
    id: 'workItem',
    from: '/project/work-items/:id',
    to: '/project/work-items/:id',
    kind: 'page',
    change: 'kept',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: true,
    carries: ['tab', 'depError', 'edit'],
    stage: 'done',
    parent: 'workItems',
  },
  {
    id: 'householdItems',
    from: '/project/household-items',
    to: '/project/household-items',
    kind: 'page',
    change: 'kept',
    section: 'Purchases',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['q', 'sortBy', 'sortOrder', 'page', 'pageSize', 'filters'],
    stage: 'done',
  },
  {
    id: 'householdItemNew',
    from: '/project/household-items/new',
    to: '/project/household-items/new',
    kind: 'page',
    change: 'kept',
    section: 'Purchases',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
    parent: 'householdItems',
  },
  {
    id: 'householdItem',
    from: '/project/household-items/:id',
    to: '/project/household-items/:id',
    kind: 'page',
    change: 'kept',
    section: 'Purchases',
    guard: 'member',
    gate: 'none',
    permanent: true,
    carries: ['tab', 'edit'],
    stage: 'done',
    parent: 'householdItems',
  },
  {
    id: 'milestones',
    from: '/project/milestones',
    to: '/project/milestones',
    kind: 'page',
    change: 'kept',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['q', 'sortBy', 'sortOrder', 'page', 'pageSize', 'filters'],
    stage: 'done',
    parent: 'workItems',
  },
  {
    id: 'milestoneNew',
    from: '/project/milestones/new',
    to: '/project/milestones/new',
    kind: 'page',
    change: 'kept',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
    parent: 'milestones',
  },
  {
    id: 'milestone',
    from: '/project/milestones/:id',
    to: '/project/milestones/:id',
    kind: 'page',
    change: 'kept',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: true,
    carries: ['tab'],
    stage: 'done',
    parent: 'milestones',
  },
  {
    id: 'budgetOverview',
    from: '/budget/overview',
    to: '/budget/overview',
    kind: 'page',
    change: 'kept',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['paymentStatus', 'deselectedSources', 'by'],
    stage: 'done',
  },
  {
    id: 'invoices',
    from: '/budget/invoices',
    to: '/budget/invoices',
    kind: 'page',
    change: 'kept',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['q', 'sortBy', 'sortOrder', 'page', 'pageSize', 'filters', 'status', 'create'],
    stage: 'done',
    parent: 'budgetOverview',
  },
  {
    id: 'invoicePaperlessReview',
    from: '/budget/invoices/new/paperless',
    to: '/budget/invoices/new/paperless',
    kind: 'page',
    change: 'kept',
    section: 'Money',
    guard: 'member',
    gate: 'paperless+ai',
    permanent: false,
    carries: ['documentId'],
    stage: 'done',
    parent: 'invoices',
  },
  {
    id: 'invoice',
    from: '/budget/invoices/:id',
    to: '/budget/invoices/:id',
    kind: 'page',
    change: 'kept',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['tab'],
    stage: 'done',
    parent: 'invoices',
  },
  {
    id: 'invoiceAutoItemize',
    from: '/budget/invoices/:id/auto-itemize/:documentId',
    to: '/budget/invoices/:id/auto-itemize/:documentId',
    kind: 'page',
    change: 'kept',
    section: 'Money',
    guard: 'member',
    gate: 'paperless+ai',
    permanent: false,
    carries: [],
    stage: 'done',
    parent: 'invoice',
  },
  {
    id: 'bankReport',
    from: '/budget/reports',
    to: '/budget/reports',
    kind: 'page',
    change: 'kept',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['sourceId', 'type'],
    stage: 'done',
    parent: 'financing',
  },
  {
    id: 'scheduleGantt',
    from: '/schedule/gantt',
    to: '/schedule/gantt',
    kind: 'page',
    change: 'kept',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['filter', 'zoom', 'group'],
    stage: 'done',
    parent: 'workItems',
  },
  {
    id: 'scheduleCalendar',
    from: '/schedule/calendar',
    to: '/schedule/calendar',
    kind: 'page',
    change: 'kept',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['calendarMode'],
    stage: 'done',
    parent: 'workItems',
  },
  {
    id: 'diary',
    from: '/diary',
    to: '/diary',
    kind: 'page',
    change: 'kept',
    section: 'Site diary',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['q', 'types', 'dateFrom', 'dateTo'],
    stage: 'done',
  },
  {
    id: 'diaryEntryNew',
    from: '/diary/new',
    to: '/diary/new',
    kind: 'page',
    change: 'kept',
    section: 'Site diary',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['areaId', 'date'],
    stage: 'done',
    parent: 'diary',
  },
  {
    id: 'diaryEntry',
    from: '/diary/:id',
    to: '/diary/:id',
    kind: 'page',
    change: 'kept',
    section: 'Site diary',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
    parent: 'diary',
  },
  {
    id: 'diaryEntryEdit',
    from: '/diary/:id/edit',
    to: '/diary/:id/edit',
    kind: 'page',
    change: 'kept',
    section: 'Site diary',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
    parent: 'diaryEntry',
  },
  {
    id: 'photos',
    from: '/photos',
    to: '/photos',
    kind: 'page',
    change: 'kept',
    section: 'Photos',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['area'],
    stage: 'done',
  },
  {
    id: 'photoSpot',
    from: '/photos/spot/:areaKey/:orientationKey',
    to: '/photos/spot/:areaKey/:orientationKey',
    kind: 'page',
    change: 'kept',
    section: 'Photos',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['photo'],
    stage: 'done',
    parent: 'photos',
  },
  {
    id: 'settingsProfile',
    from: '/settings/profile',
    to: '/settings/profile',
    kind: 'page',
    change: 'kept',
    section: 'Settings',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
    parent: 'settingsManage',
  },
  {
    id: 'settingsManage',
    from: '/settings/manage',
    to: '/settings/manage',
    kind: 'page',
    change: 'kept',
    section: 'Settings',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['tab'],
    stage: 'done',
  },
  {
    id: 'settingsUsers',
    from: '/settings/users',
    to: '/settings/users',
    kind: 'page',
    change: 'kept',
    section: 'Settings',
    guard: 'admin',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
    parent: 'settingsManage',
  },
  {
    id: 'settingsBackups',
    from: '/settings/backups',
    to: '/settings/backups',
    kind: 'page',
    change: 'kept',
    section: 'Settings',
    guard: 'admin',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
    parent: 'settingsManage',
  },
  {
    id: 'notFound',
    from: '*',
    to: '*',
    kind: 'page',
    change: 'kept',
    section: 'System',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'done',
  },
  {
    id: 'home',
    from: '/',
    to: '/',
    kind: 'page',
    change: 'redirect-becomes-page',
    section: 'Home',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'interim',
    interim: '/project/overview',
  },
  {
    id: 'financing',
    from: '/budget/financing',
    to: '/budget/financing',
    kind: 'page',
    change: 'new',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'planned',
    parent: 'budgetOverview',
  },
  {
    id: 'fundingSource',
    from: '/budget/financing/sources/:id',
    to: '/budget/financing/sources/:id',
    kind: 'page',
    change: 'new',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['tab'],
    stage: 'planned',
    parent: 'financing',
  },
  {
    id: 'grant',
    from: '/budget/financing/grants/:id',
    to: '/budget/financing/grants/:id',
    kind: 'page',
    change: 'new',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['tab'],
    stage: 'planned',
    parent: 'financing',
  },
  {
    id: 'invoiceConvert',
    from: '/budget/invoices/:id/convert',
    to: '/budget/invoices/:id/convert',
    kind: 'page',
    change: 'new',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'planned',
    parent: 'invoice',
  },
  {
    id: 'companies',
    from: '/companies',
    to: '/companies',
    kind: 'page',
    change: 'new',
    section: 'Companies',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['q', 'sortBy', 'sortOrder', 'page', 'pageSize', 'filters', 'group'],
    stage: 'interim',
    interim: '/settings/vendors',
  },
  {
    id: 'company',
    from: '/companies/:id',
    to: '/companies/:id',
    kind: 'page',
    change: 'new',
    section: 'Companies',
    guard: 'member',
    gate: 'none',
    permanent: true,
    carries: ['tab'],
    stage: 'interim',
    interim: '/settings/vendors/:id',
    parent: 'companies',
  },
  {
    id: 'areas',
    from: '/areas',
    to: '/areas',
    kind: 'page',
    change: 'new',
    section: 'Areas',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'planned',
  },
  {
    id: 'area',
    from: '/areas/:id',
    to: '/areas/:id',
    kind: 'page',
    change: 'new',
    section: 'Areas',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'planned',
    parent: 'areas',
  },
  {
    id: 'history',
    from: '/history',
    to: '/history',
    kind: 'page',
    change: 'new',
    section: 'History',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['q', 'type', 'object', 'dateFrom', 'dateTo', 'include'],
    stage: 'planned',
  },
  {
    id: 'documents',
    from: '/documents',
    to: '/documents',
    kind: 'page',
    change: 'new',
    section: 'Documents',
    guard: 'member',
    gate: 'paperless',
    permanent: false,
    carries: ['q', 'type', 'sort'],
    stage: 'planned',
  },
  {
    id: 'settingsIntegrations',
    from: '/settings/integrations',
    to: '/settings/integrations',
    kind: 'page',
    change: 'new',
    section: 'Settings',
    guard: 'admin',
    gate: 'none',
    permanent: false,
    carries: [],
    stage: 'planned',
    parent: 'settingsManage',
  },
  {
    id: 'dashboard',
    from: '/project/overview',
    to: '/',
    kind: 'redirect',
    change: 'moved',
    section: 'Home',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: 'page',
  },
  {
    id: 'householdItemEdit',
    from: '/project/household-items/:id/edit',
    to: '/project/household-items/:id?edit=overview',
    kind: 'redirect',
    change: 'retired',
    section: 'Purchases',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: 'page',
    parent: 'householdItem',
  },
  {
    id: 'budgetSources',
    from: '/budget/sources',
    to: '/budget/financing#sources',
    kind: 'redirect',
    change: 'merged',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: 'page',
    parent: 'budgetOverview',
  },
  {
    id: 'budgetSubsidies',
    from: '/budget/subsidies',
    to: '/budget/financing#grants',
    kind: 'redirect',
    change: 'merged',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: 'page',
    parent: 'budgetOverview',
  },
  {
    id: 'vendors',
    from: '/settings/vendors',
    to: '/companies',
    kind: 'redirect',
    change: 'moved',
    section: 'Companies',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: 'page',
  },
  {
    id: 'vendor',
    from: '/settings/vendors/:id',
    to: '/companies/:id',
    kind: 'redirect',
    change: 'moved',
    section: 'Companies',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: 'page',
    parent: 'vendors',
  },
  {
    id: 'project',
    from: '/project',
    to: '/',
    kind: 'redirect',
    change: 'retargeted',
    section: 'Home',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: '/project/overview',
  },
  {
    id: 'budget',
    from: '/budget',
    to: '/budget/overview',
    kind: 'redirect',
    change: 'redirect',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/budget/categories',
    to: '/settings/manage#cost-categories',
    kind: 'redirect',
    change: 'retargeted',
    section: 'Settings',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: '/settings/manage?tab=budget-categories',
  },
  {
    id: 'schedule',
    from: '/schedule',
    to: '/schedule/gantt',
    kind: 'redirect',
    change: 'retargeted',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    id: 'settings',
    from: '/settings',
    to: '/settings/manage',
    kind: 'redirect',
    change: 'retargeted',
    section: 'Settings',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: '/settings/profile',
  },
  {
    from: '/work-items',
    to: '/project/work-items',
    kind: 'redirect',
    change: 'redirect',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/work-items/new',
    to: '/project/work-items/new',
    kind: 'redirect',
    change: 'redirect',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/work-items/:id',
    to: '/project/work-items/:id',
    kind: 'redirect',
    change: 'redirect',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/household-items',
    to: '/project/household-items',
    kind: 'redirect',
    change: 'redirect',
    section: 'Purchases',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/household-items/new',
    to: '/project/household-items/new',
    kind: 'redirect',
    change: 'redirect',
    section: 'Purchases',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/household-items/:id',
    to: '/project/household-items/:id',
    kind: 'redirect',
    change: 'redirect',
    section: 'Purchases',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/household-items/:id/edit',
    to: '/project/household-items/:id?edit=overview',
    kind: 'redirect',
    change: 'retargeted',
    section: 'Purchases',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: '/project/household-items/:id/edit',
  },
  {
    from: '/invoices',
    to: '/budget/invoices',
    kind: 'redirect',
    change: 'redirect',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/invoices/:id',
    to: '/budget/invoices/:id',
    kind: 'redirect',
    change: 'redirect',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/timeline',
    to: '/schedule/gantt',
    kind: 'redirect',
    change: 'redirect',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/manage',
    to: '/settings/manage',
    kind: 'redirect',
    change: 'redirect',
    section: 'Settings',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/tags',
    to: '/areas',
    kind: 'redirect',
    change: 'retargeted',
    section: 'Areas',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: '/settings/manage',
  },
  {
    from: '/profile',
    to: '/settings/profile',
    kind: 'redirect',
    change: 'redirect',
    section: 'Settings',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/admin/users',
    to: '/settings/users',
    kind: 'redirect',
    change: 'redirect',
    section: 'Settings',
    guard: 'admin',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/budget/vendors',
    to: '/companies',
    kind: 'redirect',
    change: 'retargeted',
    section: 'Companies',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'interim',
    interim: '/settings/vendors',
  },
  {
    from: '/budget/vendors/:id',
    to: '/companies/:id',
    kind: 'redirect',
    change: 'retargeted',
    section: 'Companies',
    guard: 'member',
    gate: 'none',
    permanent: true,
    carries: ['*'],
    stage: 'interim',
    interim: '/settings/vendors/:id',
  },
  {
    from: '/schedule/milestones',
    to: '/project/milestones',
    kind: 'redirect',
    change: 'repair',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/schedule/milestones/:id',
    to: '/project/milestones/:id',
    kind: 'redirect',
    change: 'repair',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
  },
  {
    from: '/budget/financing/sources',
    to: '/budget/financing#sources',
    kind: 'redirect',
    change: 'repair',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
  },
  {
    from: '/budget/financing/grants',
    to: '/budget/financing#grants',
    kind: 'redirect',
    change: 'repair',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
  },
  {
    from: '/diary?filterMode=automatic',
    to: '/history',
    kind: 'redirect',
    change: 'query-map',
    section: 'History',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['q', 'dateFrom', 'dateTo', 'types->type'],
    stage: 'planned',
    match: {
      query: {
        filterMode: 'automatic',
      },
    },
  },
  {
    from: '/diary?filterMode=all',
    to: '/history?include=diary',
    kind: 'redirect',
    change: 'query-map',
    section: 'History',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['q', 'dateFrom', 'dateTo', 'types->type'],
    stage: 'planned',
    match: {
      query: {
        filterMode: 'all',
      },
    },
  },
  {
    from: '/budget/invoices?openOnly=true',
    to: '/budget/invoices?status=pending',
    kind: 'redirect',
    change: 'query-map',
    section: 'Money',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
    match: {
      query: {
        openOnly: 'true',
      },
    },
  },
  {
    from: '/settings/manage?tab=areas',
    to: '/areas',
    kind: 'redirect',
    change: 'query-map',
    section: 'Areas',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
    match: {
      query: {
        tab: 'areas',
      },
    },
  },
  {
    from: '/settings/manage?tab=household',
    to: '/settings/manage#house',
    kind: 'redirect',
    change: 'query-map',
    section: 'Settings',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
    match: {
      query: {
        tab: 'household',
      },
    },
  },
  {
    from: '/settings/manage?tab=trades',
    to: '/settings/manage#trades',
    kind: 'redirect',
    change: 'query-map',
    section: 'Settings',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
    match: {
      query: {
        tab: 'trades',
      },
    },
  },
  {
    from: '/settings/manage?tab=orientations',
    to: '/settings/manage#orientations',
    kind: 'redirect',
    change: 'query-map',
    section: 'Settings',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
    match: {
      query: {
        tab: 'orientations',
      },
    },
  },
  {
    from: '/settings/manage?tab=hi-categories',
    to: '/settings/manage#purchase-categories',
    kind: 'redirect',
    change: 'query-map',
    section: 'Settings',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
    match: {
      query: {
        tab: 'hi-categories',
      },
    },
  },
  {
    from: '/settings/manage?tab=budget-categories',
    to: '/settings/manage#cost-categories',
    kind: 'redirect',
    change: 'query-map',
    section: 'Settings',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
    match: {
      query: {
        tab: 'budget-categories',
      },
    },
  },
  {
    from: '/project/work-items/:id?depError=',
    to: '/project/work-items/:id?tab=timing&depError=',
    kind: 'redirect',
    change: 'query-map',
    section: 'Tasks',
    guard: 'member',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
    match: {
      query: {
        depError: true,
      },
    },
  },
  {
    from: '/budget/invoices/new/paperless (Paperless off)',
    to: '/budget/invoices?create=1',
    kind: 'redirect',
    change: 'conditional',
    section: 'Money',
    guard: 'member',
    gate: 'paperless',
    permanent: false,
    carries: ['*'],
    stage: 'done',
    match: {
      condition: 'paperless-off',
      appliesTo: ['invoicePaperlessReview'],
    },
  },
  {
    from: '/budget/invoices/new/paperless (AI off)',
    to: '/budget/invoices?create=1&documentId=',
    kind: 'redirect',
    change: 'conditional',
    section: 'Money',
    guard: 'member',
    gate: 'paperless',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
    match: {
      condition: 'ai-off',
      appliesTo: ['invoicePaperlessReview'],
    },
  },
  {
    from: '/budget/invoices/:id/auto-itemize/:documentId (Paperless or AI off)',
    to: '/budget/invoices/:id?tab=cost',
    kind: 'redirect',
    change: 'conditional',
    section: 'Money',
    guard: 'member',
    gate: 'paperless+ai',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
    match: {
      condition: 'paperless-or-ai-off',
      appliesTo: ['invoiceAutoItemize'],
    },
  },
  {
    from: '/documents (Paperless off)',
    to: '/',
    kind: 'redirect',
    change: 'conditional',
    section: 'Documents',
    guard: 'member',
    gate: 'paperless',
    permanent: false,
    carries: ['*'],
    stage: 'planned',
    match: {
      condition: 'paperless-off',
      appliesTo: ['documents'],
    },
  },
  {
    from: '/settings/users, /settings/backups, /settings/integrations (member)',
    to: '* (No access)',
    kind: 'redirect',
    change: 'conditional',
    section: 'Settings',
    guard: 'admin',
    gate: 'none',
    permanent: false,
    carries: ['*'],
    stage: 'done',
    match: {
      condition: 'not-admin',
      appliesTo: ['settingsUsers', 'settingsBackups', 'settingsIntegrations'],
    },
  },
] as const satisfies readonly RouteMapEntry[];
