/**
 * Construction diary (Bautagebuch) types.
 *
 * EPIC-13: Construction Diary
 *
 * Diary entries are either manual (created by users) or automatic (generated
 * by the system in response to state changes). Type-specific fields are stored
 * in a metadata JSON column.
 */

import type { PaginatedResponse } from './pagination.js';

// ─── Entry Types ──────────────────────────────────────────────────────────────

/** Manual entry types — created by users via the diary form. */
export type ManualDiaryEntryType =
  | 'daily_log'
  | 'site_visit'
  | 'delivery'
  | 'issue'
  | 'general_note';

/** Automatic entry types — generated by the system on state changes. */
export type AutomaticDiaryEntryType =
  | 'work_item_status'
  | 'invoice_status'
  | 'milestone_delay'
  | 'budget_breach'
  | 'auto_reschedule'
  | 'subsidy_status';

/** All diary entry types. */
export type DiaryEntryType = ManualDiaryEntryType | AutomaticDiaryEntryType;

// ─── Metadata Shapes (per entry type) ─────────────────────────────────────────

/** Weather conditions for daily logs. */
export type DiaryWeather = 'sunny' | 'cloudy' | 'rainy' | 'snowy' | 'stormy' | 'other';

/** Site visit inspection outcome. */
export type DiaryInspectionOutcome = 'pass' | 'fail' | 'conditional';

/** Issue severity levels. */
export type DiaryIssueSeverity = 'low' | 'medium' | 'high' | 'critical';

/** Issue resolution status. */
export type DiaryIssueResolution = 'open' | 'in_progress' | 'resolved';

/** Metadata for daily_log entries. */
export interface DailyLogMetadata {
  weather?: DiaryWeather | null;
  temperatureCelsius?: number | null;
  workersOnSite?: number | null;
  hasSignature?: boolean;
  signatureDataUrl?: string | null;
}

/** Metadata for site_visit entries. */
export interface SiteVisitMetadata {
  inspectorName?: string | null;
  outcome?: DiaryInspectionOutcome | null;
  hasSignature?: boolean;
  signatureDataUrl?: string | null;
}

/** Metadata for delivery entries. */
export interface DeliveryMetadata {
  vendor?: string | null;
  materials?: string[] | null;
  deliveryConfirmed?: boolean;
}

/** Metadata for issue entries. */
export interface IssueMetadata {
  severity?: DiaryIssueSeverity | null;
  resolutionStatus?: DiaryIssueResolution | null;
}

/** Metadata for general_note entries (no required fields). */
export interface GeneralNoteMetadata {
  [key: string]: unknown;
}

/** Metadata for automatic system event entries. */
export interface AutoEventMetadata {
  /** Human-readable summary of what changed. */
  changeSummary?: string | null;
  /** Previous value (for status changes). */
  previousValue?: string | null;
  /** New value (for status changes). */
  newValue?: string | null;
  /** Additional type-specific data. */
  [key: string]: unknown;
}

/** Union of all metadata shapes. */
export type DiaryEntryMetadata =
  | DailyLogMetadata
  | SiteVisitMetadata
  | DeliveryMetadata
  | IssueMetadata
  | GeneralNoteMetadata
  | AutoEventMetadata;

// ─── Source Entity Types ──────────────────────────────────────────────────────

/** Entity types that can trigger automatic diary entries. */
export type DiarySourceEntityType =
  | 'work_item'
  | 'invoice'
  | 'milestone'
  | 'budget_source'
  | 'subsidy_program';

// ─── Response Shapes ──────────────────────────────────────────────────────────

/** User summary for diary entry responses. */
export interface DiaryUserSummary {
  id: string;
  displayName: string;
}

/** Diary entry summary (used in list responses). */
export interface DiaryEntrySummary {
  id: string;
  entryType: DiaryEntryType;
  entryDate: string;
  title: string | null;
  body: string;
  metadata: DiaryEntryMetadata | null;
  isAutomatic: boolean;
  sourceEntityType: DiarySourceEntityType | null;
  sourceEntityId: string | null;
  photoCount: number;
  createdBy: DiaryUserSummary | null;
  createdAt: string;
  updatedAt: string;
}

/** Diary entry detail (used in single-item responses). */
export interface DiaryEntryDetail extends DiaryEntrySummary {
  // Detail includes all summary fields; extend if detail-only fields are added later.
}

// ─── Request Shapes ───────────────────────────────────────────────────────────

/** Request body for creating a manual diary entry. */
export interface CreateDiaryEntryRequest {
  entryType: ManualDiaryEntryType;
  entryDate: string;
  title?: string | null;
  body: string;
  metadata?: DiaryEntryMetadata | null;
}

/** Request body for updating a diary entry. */
export interface UpdateDiaryEntryRequest {
  entryDate?: string;
  title?: string | null;
  body?: string;
  metadata?: DiaryEntryMetadata | null;
}

// ─── Query & List Response ────────────────────────────────────────────────────

/** Query parameters for GET /api/diary-entries. */
export interface DiaryEntryListQuery {
  page?: number;
  pageSize?: number;
  type?: string;
  dateFrom?: string;
  dateTo?: string;
  automatic?: boolean;
  q?: string;
}

/** Paginated diary entry list response. */
export type DiaryEntryListResponse = PaginatedResponse<DiaryEntrySummary>;
