/**
 * Construction diary (Bautagebuch) types.
 *
 * EPIC-13: Construction Diary
 *
 * Diary entries are either manual (created by users) or automatic (generated
 * by the system in response to state changes). Type-specific fields are stored
 * in a metadata JSON column.
 */

import type { PaginatedResponse } from './pagination.js';
import type { AreaSummary } from './area.js';

// ─── Entry Types ──────────────────────────────────────────────────────────────

/** Manual entry types — created by users via the diary form. */
export type ManualDiaryEntryType =
  | 'daily_log'
  | 'site_visit'
  | 'delivery'
  | 'issue'
  | 'general_note';

/** Automatic entry types — generated by the system on state changes. */
export type AutomaticDiaryEntryType =
  | 'work_item_status'
  | 'invoice_status'
  | 'milestone_delay'
  | 'budget_breach'
  | 'auto_reschedule'
  | 'subsidy_status'
  | 'invoice_created';

/** All diary entry types. */
export type DiaryEntryType = ManualDiaryEntryType | AutomaticDiaryEntryType;

// ─── Metadata Shapes (per entry type) ─────────────────────────────────────────

/** Signature entry in diary metadata. */
export interface DiarySignatureEntry {
  signerName: string;
  signerType: 'self' | 'vendor';
  signatureDataUrl: string;
  signedAt?: string;
}

/** Weather conditions for daily logs. */
export type DiaryWeather = 'sunny' | 'cloudy' | 'rainy' | 'snowy' | 'stormy' | 'other';

/** Site visit inspection outcome. */
export type DiaryInspectionOutcome = 'pass' | 'fail' | 'conditional';

/** Issue severity levels. */
export type DiaryIssueSeverity = 'low' | 'medium' | 'high' | 'critical';

/** Issue resolution status. */
export type DiaryIssueResolution = 'open' | 'in_progress' | 'resolved';

/** Metadata for daily_log entries. */
export interface DailyLogMetadata {
  weather?: DiaryWeather | null;
  temperatureCelsius?: number | null;
  workersOnSite?: number | null;
  /** Optional vendor reference by ID. Stored as vendorId; vendorName is resolved server-side at read time. */
  vendorId?: string | null;
  /** Denormalized vendor name, resolved server-side at read time from vendorId. Never sent by the client. */
  vendorName?: string | null;
  /** Work start time in HH:mm (24h) format. */
  workStart?: string | null;
  /** Work end time in HH:mm (24h) format. Must be strictly after workStart when both present. */
  workEnd?: string | null;
  signatures?: DiarySignatureEntry[] | null;
}

/** Metadata for site_visit entries. */
export interface SiteVisitMetadata {
  inspectorName?: string | null;
  outcome?: DiaryInspectionOutcome | null;
  signatures?: DiarySignatureEntry[] | null;
}

/** Metadata for delivery entries. */
export interface DeliveryMetadata {
  vendor?: string | null;
  materials?: string[] | null;
  deliveryConfirmed?: boolean;
}

/** Metadata for issue entries. */
export interface IssueMetadata {
  severity?: DiaryIssueSeverity | null;
  resolutionStatus?: DiaryIssueResolution | null;
}

/** Metadata for general_note entries (no required fields). */
export interface GeneralNoteMetadata {
  [key: string]: unknown;
}

/** Metadata for automatic system event entries. */
export interface AutoEventMetadata {
  /** Human-readable summary of what changed. */
  changeSummary?: string | null;
  /** Previous value (for status changes). */
  previousValue?: string | null;
  /** New value (for status changes). */
  newValue?: string | null;
  /** Target date for milestone (used in milestone delay events). */
  targetDate?: string;
  /** Projected date for milestone (used in milestone delay events). */
  projectedDate?: string;
  /** Number of days delayed (used in milestone delay events). */
  delayDays?: number;
  /** Additional type-specific data. */
  [key: string]: unknown;
}

/** Union of all metadata shapes. */
export type DiaryEntryMetadata =
  | DailyLogMetadata
  | SiteVisitMetadata
  | DeliveryMetadata
  | IssueMetadata
  | GeneralNoteMetadata
  | AutoEventMetadata;

// ─── Source Entity Types ──────────────────────────────────────────────────────

/** Entity types that can trigger automatic diary entries. */
export type DiarySourceEntityType =
  | 'work_item'
  | 'invoice'
  | 'milestone'
  | 'budget_source'
  | 'subsidy_program';

// ─── Status ───────────────────────────────────────────────────────────────────

/**
 * Lifecycle status of a diary entry.
 *
 * - `draft`: work-in-progress, auto-created on first interaction in the create
 *   flow. Server-side validation is relaxed (body and entryDate may be missing
 *   or empty; type-specific required metadata is not enforced). Drafts are
 *   excluded from dashboard aggregations and any export/report paths by
 *   default. Auto-pruned by a cron job after a configurable retention window.
 * - `saved`: finalized entry. Full validation enforced. This is the default
 *   for backwards compatibility — all rows created before migration 0033
 *   default to `'saved'`.
 *
 * See ADR-022 (Diary Drafts).
 */
export type DiaryEntryStatus = 'draft' | 'saved';

// ─── Response Shapes ──────────────────────────────────────────────────────────

/** User summary for diary entry responses. */
export interface DiaryUserSummary {
  id: string;
  displayName: string;
}

/** Diary entry summary (used in list responses). */
export interface DiaryEntrySummary {
  id: string;
  entryType: DiaryEntryType;
  /**
   * Lifecycle status. `'saved'` for backwards-compatible default; `'draft'`
   * for in-progress entries created by the auto-draft flow.
   */
  status: DiaryEntryStatus;
  entryDate: string;
  title: string | null;
  body: string;
  metadata: DiaryEntryMetadata | null;
  isAutomatic: boolean;
  isSigned: boolean;
  sourceEntityType: DiarySourceEntityType | null;
  sourceEntityId: string | null;
  sourceEntityArea: AreaSummary | null;
  sourceEntityTitle: string | null;
  photoCount: number;
  createdBy: DiaryUserSummary | null;
  createdAt: string;
  updatedAt: string;
}

/** Diary entry detail (used in single-item responses). */
export interface DiaryEntryDetail extends DiaryEntrySummary {
  // Detail includes all summary fields; extend if detail-only fields are added later.
}

// ─── Request Shapes ───────────────────────────────────────────────────────────

/**
 * Request body for creating a manual diary entry.
 *
 * When `status` is omitted or `'saved'`, the server enforces full validation:
 * `body` must be a non-empty string, `entryDate` must be an ISO date, and
 * type-specific required metadata fields must be present.
 *
 * When `status === 'draft'`, validation is relaxed (see ADR-022):
 * - `body` may be omitted or empty
 * - `entryDate` may be omitted (server defaults to today)
 * - Type-specific required fields are not enforced
 * - Metadata shape validation (enum values, types) is still enforced
 *
 * `entryType` is always required and immutable after creation.
 */
export interface CreateDiaryEntryRequest {
  entryType: ManualDiaryEntryType;
  /**
   * Lifecycle status. Defaults to `'saved'` (backwards-compatible). Pass
   * `'draft'` to create an in-progress entry with relaxed validation.
   */
  status?: DiaryEntryStatus;
  /** Required when `status === 'saved'`. Optional for drafts (defaults to today). */
  entryDate?: string;
  title?: string | null;
  /** Required when `status === 'saved'`. Optional/empty for drafts. */
  body?: string;
  metadata?: DiaryEntryMetadata | null;
}

/**
 * Request body for updating a diary entry.
 *
 * Validation rules mirror create:
 * - If the entry is currently `status === 'draft'`, validation is relaxed.
 * - If the entry is `status === 'saved'`, full validation applies and the
 *   entry cannot be reverted to a draft (no `status` field accepted here).
 *
 * Use `PATCH /api/diary-entries/:id/promote` to transition draft → saved.
 * `entryType` is immutable and cannot be changed via this endpoint.
 */
export interface UpdateDiaryEntryRequest {
  entryDate?: string;
  title?: string | null;
  body?: string;
  metadata?: DiaryEntryMetadata | null;
}

/**
 * Request body for promoting a draft to a saved entry.
 *
 * Optional final field overrides — if any of these are provided, they are
 * applied to the draft before the promotion validation runs (so the client
 * can save and promote in one call). All fields are optional; the draft's
 * current values are used otherwise.
 *
 * After promotion, the entry's `status` is `'saved'` and the full
 * saved-entry validation has passed. A failed promotion returns
 * `400 VALIDATION_ERROR` and leaves the entry as a draft.
 */
export interface PromoteDiaryEntryRequest {
  entryDate?: string;
  title?: string | null;
  body?: string;
  metadata?: DiaryEntryMetadata | null;
}

// ─── Query & List Response ────────────────────────────────────────────────────

/** Query parameters for GET /api/diary-entries. */
export interface DiaryEntryListQuery {
  page?: number;
  pageSize?: number;
  type?: string;
  dateFrom?: string;
  dateTo?: string;
  automatic?: boolean;
  /**
   * Filter by lifecycle status. When omitted, both drafts and saved entries
   * are returned (the timeline view's default — drafts are part of the user's
   * "inbox"). Callers that surface diary entries outside the timeline
   * (dashboard tile, exports, reports) MUST pass `status=saved` explicitly.
   * See ADR-022 for the read-path checklist.
   */
  status?: DiaryEntryStatus;
  q?: string;
}

/** Paginated diary entry list response. */
export type DiaryEntryListResponse = PaginatedResponse<DiaryEntrySummary>;
