/**
 * Machine-readable error codes used across all API error responses.
 */
export type ErrorCode =
  | 'NOT_FOUND'
  | 'ROUTE_NOT_FOUND'
  | 'VALIDATION_ERROR'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'CONFLICT'
  | 'INTERNAL_ERROR'
  | 'SETUP_COMPLETE'
  | 'INVALID_CREDENTIALS'
  | 'ACCOUNT_DEACTIVATED'
  | 'SELF_DEACTIVATION'
  | 'LAST_ADMIN'
  | 'OIDC_NOT_CONFIGURED'
  | 'OIDC_ERROR'
  | 'EMAIL_CONFLICT'
  | 'CIRCULAR_DEPENDENCY'
  | 'DUPLICATE_DEPENDENCY'
  | 'CATEGORY_IN_USE'
  | 'VENDOR_IN_USE'
  | 'BUDGET_SOURCE_IN_USE'
  | 'SUBSIDY_PROGRAM_IN_USE'
  | 'BUDGET_LINE_IN_USE';
